# Support the authors coffee addiction to fuel new features and updates!
# Buy Me a Coffee: https://www.buymeacoffee.com/andrewhiser
github: ahiser24
buy_me_a_coffee: andrewhiser
# I hope you enjoy the app and find it useful!